"""Gatekeeper tools — read-only access to GATEKEEPER/ turnin logs.

The GATEKEEPER/ directory at the repo root contains per-turnin log files
generated by the gatekeeper pipeline.  These tools provide structured
access to those logs for debugging turnin failures, inspecting pre-turnin
checks, and reviewing submission history.

All tools are read-only.  A path-traversal guard restricts access to files
under $WORKAREA/GATEKEEPER/ only.
"""

from __future__ import annotations

import glob
import logging
import os
import re
from typing import Optional

from mcp.server.fastmcp import FastMCP

logger = logging.getLogger("turnin-mcp.gatekeeper")


def _gk_dir(repo_root: str) -> str:
    """Return the absolute path to the GATEKEEPER directory."""
    workarea = os.environ.get("WORKAREA", repo_root)
    return os.path.join(workarea, "GATEKEEPER")


def _safe_read(filepath: str, gk_base: str, max_bytes: int = 200_000) -> str:
    """Read a file if it resides under *gk_base*; return content or error."""
    real_file = os.path.realpath(filepath)
    real_base = os.path.realpath(gk_base)
    if not (real_file.startswith(real_base + os.sep) or real_file == real_base):
        return "Error: path traversal not allowed."
    if not os.path.isfile(filepath):
        return f"File not found: {os.path.basename(filepath)}"
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
            content = fh.read(max_bytes)
        if len(content) == max_bytes:
            content += "\n... (truncated at 200 KB)"
        return content
    except OSError as exc:
        return f"Error reading file: {exc}"


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------
def register_gatekeeper_tools(mcp: FastMCP, repo_root: str) -> None:
    """Register GATEKEEPER log-reading tools on the MCP server."""

    @mcp.tool()
    def gatekeeper_list_turnins() -> str:
        """List all turnin sessions recorded in the GATEKEEPER/ directory.

        Returns a table of turnin dates, IDs, and available log types.
        Use this to discover what turnin history exists.

        When to use: Exploring past turnin attempts, finding a turnin date
        or ID to inspect further.
        Keywords: gatekeeper, turnin log, history, turnin sessions, GATEKEEPER.
        """
        gk = _gk_dir(repo_root)
        if not os.path.isdir(gk):
            return f"GATEKEEPER directory not found at {gk}"

        # Find turnin log files — they have the date in the filename
        log_pattern = os.path.join(gk, "turnin.????-??-??_??-??-??.log")
        logs = sorted(glob.glob(log_pattern))

        if not logs:
            return "No turnin logs found in GATEKEEPER/."

        lines = [
            "| Date | Log File | ID File | Pre-Turnin | Post-Submit |",
            "| --- | --- | --- | --- | --- |",
        ]

        for log_path in logs:
            fname = os.path.basename(log_path)
            # Extract date from turnin.YYYY-MM-DD_HH-MM-SS.log
            date_match = re.search(r"turnin\.(\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})\.log", fname)
            date_str = date_match.group(1) if date_match else fname

            # Check for corresponding files
            id_file = log_path.replace(".log", ".id")
            has_id = "Yes" if os.path.isfile(id_file) else "No"

            # Pre-turnin logs use a PID, find ones nearby in time
            preturnin_logs = glob.glob(os.path.join(gk, "gk_pre_turnin_checks.*.log"))
            has_preturnin = "Yes" if preturnin_logs else "—"

            postsub_logs = glob.glob(os.path.join(gk, "gk_post_submit_hook.*.log"))
            has_postsub = "Yes" if postsub_logs else "—"

            lines.append(
                f"| {date_str} | {fname} | {has_id} | {has_preturnin} | {has_postsub} |"
            )

        # Also list PIDs from files_changed
        pid_files = glob.glob(os.path.join(gk, "turnin_files_changed.*"))
        pids = sorted({
            os.path.basename(f).split(".")[-1]
            for f in pid_files
            if os.path.basename(f).split(".")[-1].isdigit()
        })

        if pids:
            lines.append(f"\nKnown turnin PIDs: {', '.join(pids)}")

        return "\n".join(lines)

    @mcp.tool()
    def gatekeeper_read_log(
        identifier: str = "",
        log_type: str = "turnin",
    ) -> str:
        """Read a specific log file from the GATEKEEPER/ directory.

        Args:
            identifier: A date string (YYYY-MM-DD_HH-MM-SS), PID number,
                        or "latest" (default if empty) to read the most
                        recent file of the given type.
            log_type: Type of log to read.  One of:
                "turnin"        — main turnin log (turnin.*.log)
                "id"            — turnin ID (turnin.*.id)
                "env"           — environment snapshot (turnin.env*.log)
                "preturnin"     — pre-turnin check results (gk_pre_turnin_checks.*.log)
                "post_submit"   — post-submit hook log (gk_post_submit_hook.*.log)
                "files_changed" — files changed in turnin (turnin_files_changed.*)
                "changelog"     — git changelog (turnin_changelog.*)
                "code_review"   — code review URL (code_review_url.*.txt)

        Returns the file content.

        When to use: Debugging a turnin failure, reviewing pre-turnin check
        results, or inspecting what files were in a turnin.
        Keywords: gatekeeper, log, pre-turnin, post-submit, files changed,
        turnin failure, debug.
        """
        gk = _gk_dir(repo_root)
        if not os.path.isdir(gk):
            return f"GATEKEEPER directory not found at {gk}"

        if not identifier or identifier.lower() == "latest":
            identifier = ""  # will pick latest match

        # Map log_type to filename patterns
        type_patterns = {
            "turnin":        "turnin.*.log",
            "id":            "turnin.*.id",
            "env":           "turnin.env*.log",
            "preturnin":     "gk_pre_turnin_checks.*.log",
            "post_submit":   "gk_post_submit_hook.*.log",
            "files_changed": "turnin_files_changed.*",
            "changelog":     "turnin_changelog.*",
            "code_review":   "code_review_url.*.txt",
        }

        if log_type not in type_patterns:
            return (
                f"Unknown log_type '{log_type}'. "
                f"Allowed: {', '.join(sorted(type_patterns))}"
            )

        pattern = type_patterns[log_type]
        candidates = sorted(glob.glob(os.path.join(gk, pattern)))

        if not candidates:
            return f"No {log_type} logs found in GATEKEEPER/."

        if identifier:
            # Filter by identifier (date substring or PID)
            filtered = [
                c for c in candidates
                if identifier in os.path.basename(c)
            ]
            if not filtered:
                return (
                    f"No {log_type} log matching '{identifier}'. "
                    f"Available: {', '.join(os.path.basename(c) for c in candidates)}"
                )
            target = filtered[-1]  # latest match
        else:
            target = candidates[-1]  # latest overall

        header = f"=== {os.path.basename(target)} ===\n\n"
        return header + _safe_read(target, gk)

    @mcp.tool()
    def gatekeeper_latest_status() -> str:
        """Get a summary of the most recent turnin attempt.

        Reads the latest turnin log and pre-turnin check log, and
        extracts the turnin ID if available.  Provides a quick status
        overview without needing to know specific dates or PIDs.

        When to use: "What happened with my last turnin?", "Did my
        turnin pass?", "What was my last turnin ID?"
        Keywords: latest turnin, last turnin, status, result, pass, fail.
        """
        gk = _gk_dir(repo_root)
        if not os.path.isdir(gk):
            return f"GATEKEEPER directory not found at {gk}"

        sections: list[str] = []

        # Latest turnin log
        turnin_logs = sorted(glob.glob(os.path.join(gk, "turnin.????-??-??_??-??-??.log")))
        if turnin_logs:
            latest_log = turnin_logs[-1]
            fname = os.path.basename(latest_log)
            content = _safe_read(latest_log, gk, max_bytes=50_000)
            sections.append(f"=== Latest Turnin Log: {fname} ===\n\n{content}")

            # Check for ID file
            id_file = latest_log.replace(".log", ".id")
            if os.path.isfile(id_file):
                id_content = _safe_read(id_file, gk, max_bytes=1000)
                sections.append(f"=== Turnin ID ===\n\n{id_content}")
        else:
            sections.append("No turnin logs found.")

        # Latest pre-turnin check
        preturnin_logs = sorted(glob.glob(os.path.join(gk, "gk_pre_turnin_checks.*.log")))
        if preturnin_logs:
            latest_pt = preturnin_logs[-1]
            fname = os.path.basename(latest_pt)
            content = _safe_read(latest_pt, gk, max_bytes=50_000)
            sections.append(f"=== Latest Pre-Turnin Check: {fname} ===\n\n{content}")

        # Latest code review URL
        cr_files = sorted(glob.glob(os.path.join(gk, "code_review_url.*.txt")))
        if cr_files:
            cr_content = _safe_read(cr_files[-1], gk, max_bytes=1000)
            sections.append(f"=== Code Review URL ===\n\n{cr_content}")

        return "\n\n".join(sections)
