"""JasperGold command tools — build JG batch commands for the build-run agent."""

from __future__ import annotations

import json
import logging
import os
import shlex

from mcp.server.fastmcp import FastMCP

logger = logging.getLogger("runfv-mcp.jg_cmd")

_JG_BIN = "jg"

_ALLOWED_APPS = frozenset({
    "fpv", "cdc", "lpv", "sec", "superlint", "conn",
    "cov", "spv", "xprop", "fsv", "csr", "rvv", "unr",
})


def _sanitize_extra_args(extra_args: str) -> str:
    """Parse extra_args through shlex to neutralise shell metacharacters."""
    if not extra_args:
        return ""
    try:
        tokens = shlex.split(extra_args)
    except ValueError as exc:
        raise ValueError(f"Invalid extra_args: {exc}") from exc
    return " ".join(shlex.quote(t) for t in tokens)


def _validate_name(name: str, label: str) -> str | None:
    """Return an error string if name contains invalid characters."""
    if not name:
        return None
    if not all(c.isalnum() or c in "_-" for c in name):
        return f"Invalid {label} name: {name!r}"
    return None


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------

def register_jg_cmd_tools(mcp: FastMCP, repo_root: str) -> None:
    """Register JasperGold command-builder tools on the MCP server."""

    @mcp.tool()
    async def jg_cmd(
        tcl_commands: str,
        app: str = "fpv",
        dut: str = "",
        proof: str = "",
        extra_jg_args: str = "",
    ) -> str:
        """Build a JasperGold batch command and Tcl script content.

        Returns a JSON object with the shell command(s) and Tcl script
        that should be executed by the @build-run agent (via terminal or
        the run_make / run_grdlbuild MCP tools). This tool does NOT
        execute commands itself.

        Args:
            tcl_commands: Tcl commands to execute (semicolon or newline
                separated).
                Examples:
                  "prove -all"
                  "prove -property {my_prop}; report -summary"
                  Multi-line scripts are supported.
            app: JasperGold application to launch. One of: fpv, cdc, lpv,
                 sec, superlint, conn, cov, spv, xprop, fsv, csr, rvv,
                 unr (default: fpv).
            dut: DUT name for proof loading (e.g. "memss_pma"). Required
                 when proof is specified.
            proof: Proof name to load before executing commands (e.g.
                   "memss_pma_boot_err_checks_tm"). When set, a
                   preliminary run_fv load-proof command is included.
            extra_jg_args: Additional JasperGold command-line arguments.

        Returns a JSON object with:
          - tcl_script: the Tcl script content to write to a .tcl file
          - commands: ordered list of shell commands to run
          - cwd: the working directory ($WORKAREA)
          - notes: any additional guidance for the executing agent

        When to use: Building proof commands, checking properties,
        generating reports, or any JG Tcl operation in batch.
        Keywords: jasper, jaspergold, jg, tcl, prove, fpv, formal, batch.
        """
        # Validate inputs
        tcl_body = tcl_commands.strip()
        if not tcl_body:
            return json.dumps({"error": "No Tcl commands provided."})

        if app not in _ALLOWED_APPS:
            return json.dumps({
                "error": f"Invalid app: {app!r}. "
                         f"Allowed: {', '.join(sorted(_ALLOWED_APPS))}"
            })

        if proof and not dut:
            return json.dumps({
                "error": "When proof is specified, dut is also required."
            })

        for name, label in [(dut, "dut"), (proof, "proof")]:
            err = _validate_name(name, label)
            if err:
                return json.dumps({"error": err})

        workarea = os.environ.get("WORKAREA", repo_root)

        # Build the Tcl script content
        tcl_script = "\n".join([
            "# Auto-generated by runfv-mcp jg_cmd tool",
            tcl_body,
            "",
            "exit -force",
        ])

        # Build the ordered list of commands
        commands: list[str] = []
        notes: list[str] = []

        # Step 1 (optional): load proof via run_fv
        if proof:
            load_cmd = (
                f"run_fv load-proof"
                f" -dut {shlex.quote(dut)}"
                f" -p {shlex.quote(proof)}"
                f" -b"
            )
            commands.append(load_cmd)
            notes.append(
                f"Step 1: Load proof '{proof}' for DUT '{dut}' "
                f"(must complete before JG launch)."
            )

        # Step 2: write the Tcl script and run JG
        tcl_filename = f"jg_cmd_{proof or 'batch'}.tcl"
        tcl_dir = "$WORKAREA/output/formal/jg_cmd"
        tcl_path = f"{tcl_dir}/{tcl_filename}"

        commands.append(f"mkdir -p {tcl_dir}")

        jg_args = [_JG_BIN, f"-{app}", "-batch", "-no_gui"]

        if proof:
            proj_dir = (
                f"$WORKAREA/output/formal/{shlex.quote(proof)}"
                f"/compile/jgproject"
            )
            jg_args.extend(["-proj", proj_dir, "-acquire_proj"])
            notes.append(
                f"The -proj flag assumes the proof was already built. "
                f"If {proj_dir} does not exist, omit -proj and -acquire_proj."
            )

        jg_args.extend(["-tcl", tcl_path])

        jg_cmd_str = " ".join(shlex.quote(a) for a in jg_args)
        if extra_jg_args:
            try:
                jg_cmd_str += f" {_sanitize_extra_args(extra_jg_args)}"
            except ValueError as exc:
                return json.dumps({"error": f"Invalid extra_jg_args: {exc}"})

        commands.append(jg_cmd_str)
        notes.append(
            "Write the tcl_script content to the file path shown, "
            "then run the JG command. Use the @build-run agent to "
            "execute these commands in a CTH-configured terminal."
        )

        return json.dumps({
            "tcl_script": tcl_script,
            "tcl_filename": tcl_filename,
            "tcl_dir": tcl_dir,
            "commands": commands,
            "cwd": workarea,
            "notes": notes,
        }, indent=2)
